service: post-upload-service

app: post-upload-app
org: lawrenceforsytheiii

custom:
  function: posts-${self:provider.stage}-function-20200311
  bucket: posts-${self:provider.stage}-bucket-20200311
  table: posts-${self:provider.stage}-table-20200311

provider:
  name: aws
  runtime: nodejs10.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

stage: dev
region: us-east-1

functions:
  upload:
    handler: handler.upload
    name: ${self:custom.function}
    environment:
      BUCKET: ${self:custom.bucket}

resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
          - AttributeName: title
            AttributeType: S
          - AttributeName: body
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: userId
            KeyType: RANGE
        # Set the capacity to auto-scale
        BillingMode: PAY_PER_REQUEST
    PostsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
